name: "Extra Paragraphs"
type: "Paragraphs"
description: 'Provides editor-friendly Paragraph types such as Highlight and Collapse, including fields and display settings for quick page composition.'
install:
  - file
  - image
  - link
  - paragraphs
  - text
config:
  strict: false
